GET http://localhost:8080/daily/api/weather/location?name=Wroc%C5%82aw&language=pl

### Get geolocation by name
GET http://localhost:8080/daily/api/weather/location?name=Warszawa&language=pl

### Get geolocation by name
GET {{url}}/api/weather/location?name=Warszawa&language=pl&provider=accuweather
Accept: application/json

### Forecast (open geo weather)
GET {{url}}/api/weather/open/forecast?lat=51.1&lon=17.03333
Accept: application/json

### Forecast (accuweather)
GET {{url}}/api/weather/accu/forecast?locationKey=274663
Accept: application/json

### GET location
GET https://q-programming.pl/daily/api/weather/location?name=Wroc%C5%82aw&language=pl